<a href="https://colab.research.google.com/github/KaranKendre11/pytorch-learning/blob/main/Intro_to_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
import numpy as np

In [5]:
my_list = [[1,2,3,4],[5,6,7,8]]
my_list

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [10]:
# Numpy arrays
np1 = np.random.randint(low=2, high=6,size=(3,4))
np1

array([[5, 5, 4, 5],
       [5, 3, 2, 4],
       [3, 4, 2, 2]])

In [11]:
# Tensors [powerful than numpy]
tensor_2d = torch.rand(3,4)
tensor_2d

tensor([[0.8316, 0.4992, 0.6732, 0.1559],
        [0.5667, 0.7667, 0.4736, 0.1928],
        [0.8004, 0.3399, 0.7853, 0.2955]])

In [12]:
# Conversion from numpy - > tensor
my_tensor = torch.tensor(np1)
my_tensor

tensor([[5, 5, 4, 5],
        [5, 3, 2, 4],
        [3, 4, 2, 2]])