<a href="https://colab.research.google.com/github/KaranKendre11/pytorch-learning/blob/main/Intro_to_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
import numpy as np

In [5]:
my_list = [[1,2,3,4],[5,6,7,8]]
my_list

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [10]:
# Numpy arrays
np1 = np.random.randint(low=2, high=6,size=(3,4))
np1

array([[5, 5, 4, 5],
       [5, 3, 2, 4],
       [3, 4, 2, 2]])

In [11]:
# Tensors [powerful than numpy]
tensor_2d = torch.rand(3,4)
tensor_2d

tensor([[0.8316, 0.4992, 0.6732, 0.1559],
        [0.5667, 0.7667, 0.4736, 0.1928],
        [0.8004, 0.3399, 0.7853, 0.2955]])

In [12]:
# Conversion from numpy - > tensor
my_tensor = torch.tensor(np1)
my_tensor

tensor([[5, 5, 4, 5],
        [5, 3, 2, 4],
        [3, 4, 2, 2]])

In [13]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
my_torch = my_torch.reshape(2,5) # if we do reshape(2, -1) it chooses a random
                                 # number to divide
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [15]:
my_torch = my_torch.view(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [23]:
# updation in tensor reflects in all other copies of it
my_torch = torch.arange(10)

my_torch2 = my_torch.reshape(5,2)
# before update
print(my_torch2)
# updating
my_torch[1] = 3232
# after update
print(my_torch2)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
tensor([[   0, 3232],
        [   2,    3],
        [   4,    5],
        [   6,    7],
        [   8,    9]])


In [29]:
my_torch2[:,:1]

tensor([[0],
        [2],
        [4],
        [6],
        [8]])

In [30]:
# TENSOR MATH OPERATIONS
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [31]:
# Addition longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [32]:
# Subtract
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [35]:
# Sub Longhand
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [36]:
# Mul
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [37]:
# Mul longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [38]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [39]:
# Division longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [40]:
# Remainder mod
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [42]:
# Remainder longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [44]:
# Exponents / pow longhand
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [46]:
# Reassignment "_"
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [47]:
# Checking if reassignment changed tensor_a
tensor_a

tensor([ 6,  8, 10, 12])